config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about' => 'homes#about', as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update ]
  patch 'books/:id' => 'books#update', as: 'update_book'
  resources :users, only: [:show, :edit, :update, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :profile_image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  
  def first_sign_in?
   if sign_in_count == 1
 
    return true
  else
    # サインイン回数が1以外の場合、初回サインインではない
    return false
  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
   def after_sign_in_path_for(resource)
     user_path(current_user.id)
   end

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  def new
    @user = current_user
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = current_user
    @book.user = current_user
    if @book.save
     flash[:notice] = 'You have created book successfully.'
     redirect_to book_path(@book)
    else
     @books = Book.all
     render :index
    end
  end

  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = current_user
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
     redirect_to @book, notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
    def is_matching_login_user
     @book = Book.find(params[:id])
     unless @book.user.id == current_user.id
      redirect_to books_path
     end
    end
  
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/controllers/custom_sessions_controller.rb
# app/controllers/custom_sessions_controller.rb
class CustomSessionsController < Devise::SessionsController
  def destroy
    super
    set_flash_message! :notice , :sign_out if sign_out
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @book = Book.create
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
      render :edit
    end
  end
  
  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @book = Book.create
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/custom_sessions_helper.rb
module CustomSessionsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
  <thead>
   <th></th>
   <th>Title</th>
   <th>Body</th>
   <th colspan="3"></th>
  </thead>
  
  <tbody>
   <% books.each do |book| %>
   <tr>
   <td><%= link_to image_tag(book.user.profile_image), user_path(book.user) %></td>
   <td><%= link_to book.title, book_path(book.id) %></td>
   <td><%= book.body %></td>
   </tr>
   <% end %>
  </tbody>
  </table>

app/views/books/_new.html.erb
 <h2 class="mt-3">New book</h2>
 
 <%= form_with model: @book, url: books_path, method: :post do |f| %>
  <div class="form-group">
    <label for="title">Title</label>
    <input class="form-control book_title" type="text" name="book[title]" id="book_title">
  </div>
  <div class="form-group">
    <label for="body">Opinion</label>
    <textarea class="form-control book_body" name="book[body]" id="book_body" ></textarea>
  </div>
  <div class="actions">
    <%= f.submit "Create Book", class: "btn btn-success" %>
  </div>
 <% end %>

app/views/books/edit.html.erb
 <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h1>Editing Book</h1>
   <% if @book.errors.any? %>
   <%= @book.errors.count %>errors prohibited this obj from being saved:
    <ul>
   <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
   <% end %>
    </ul>
   <% end %>
   
   <%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>
   <div class="form-group">
   <label for="book_title">Title</label>
   <%= f.text_field :title, class: "form-control"  %>
   </div>
   <div class="form-group">
   <label for="book_title">Opinion</label><br>
    <%= f.text_area :body, class: "form-control" %>
   </div>
   <button class="btn btn-success" type="submit">Update Book</button>
   <% end %>
   <br><%= link_to "Show", book_path(@book.id) %>|<a href= "/books">Back</a>
  </div>

app/views/books/index.html.erb
　<% if @book.errors.any? %>
  <h4><%= @book.errors.count %>errors prohibited this obj from being saved:</h4>
  <ul>
   <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
   <% end %>
  </ul>
 　<% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
   <div class="col-md-3">
    <%= render 'users/user_info', user: @user %>
    <%= render 'new', book: @book %>
  </div>
  <div class="col-md-8 offset-md-1">
  <%= render 'list', books: @books %>
  </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
    <%= render 'users/user_info', user: @book.user %>
    <%= render 'new', book: @book %>
  </div>
  <div class="col-md-8 offset-md-1">
   <h2>Book detail</h2>
   <table class="table">
   <tbody>
    <tr>
     <td><%= link_to image_tag(@book.user.profile_image, size: "100x100"), user_path(@book.user) %><br>
     <%= link_to @book.user.name, user_path(@book.user) %></td>
     <td><%= link_to @book.title, book_path(@book.id) %></td>
     <td><%= @book.body %></td>
     <% if @book.user == current_user %>
     <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
     <td><%= link_to "Destroy", book_path(@book), method: :delete, class: "btn btn-sm btn-danger", data: { confirm: "本当に削除しますか?" } %></td>
     <% end %>
    </tr>
   </tbody>
  </table>
  </div>
 </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
     Welcome to 
     <i class="fas fa-book" aria-hidden="true"></i>
      <strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to 
      <i class="fas fa-book" aria-hidden="true"></i>
      <strong>Bookers</strong> !!</h1>
      <p>In
      <i class="fas fa-book" aria-hidden="true"></i>
      <strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions<br>
      about various books!</p>
      </p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">
            Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">
            Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_notification.html.erb
<div class="Notification">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: key %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" >

　　<script src="https://kit.fontawesome.com/98ef09a9a3.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
  <header>
    <nav class= "navbar navbar-expand-lg navbar-dark bg-dark">
     <div class="container">
         <a class="navbar-brand" href="/">
             <span>Bookers</span>
         </a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation" >
             <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarNavDropdown">
             <ul class="navbar-nav ml-auto">
             <% if user_signed_in? %>
             <li class="nav-item">
              <a class="nav-link text-light" href="<%= user_path(current_user) %>">
                <i class="fas fa-home" aria-hidden="true"></i>
                Home
              </a>
             </li>
             <li class="nav-item">
              <a class="nav-link text-light" href="/users">
                <i class="fas fa-users" aria-hidden="true"></i>
                Users
              </a>
             </li>
             <li class="nav-item">
              <a class="nav-link text-light" href="/books">
                <i class="fas fa-book-open" aria-hidden="true"></i>
                Books
              </a>
             </li>
             <li class="nav-item">
              <a class="nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out" >
                <i class="fas fa-sign-out-alt" aria-hidden="true"></i>
                Log out
              </a>
             </li>
             <% else %>
             <li class="nav-item">
              <a class="nav-link text-light" href="/">
                <i class="fas fa-home" aria-hidden="true"></i>
                Home
              </a>
             </li>
             <li class="nav-item">
              <a class="nav-link text-light" href="/home/about">
                <i class="fas fa-link" aria-hidden="true"></i>
                About
              </a>
             </li>
             <li class="nav-item">
              <a class="nav-link text-light" href="<%= new_user_registration_path %>">
                <i class="fas fa-user-plus" aria-hidden="true"></i>
                Sign up
              </a>
             </li>
              <li class="nav-item">
              <a class="nav-link text-light" href="<%= new_user_session_path %>">
                <i class="fas fa-sign-in-alt" aria-hidden="true"></i>
                Log in
              </a>
             </li>
             <% end %>
             </ul>
         </div>
     </div>
    </nav>
  </header>

  <body>
　  <main>
　    <%= render 'layouts/notification' %>
　    <%= yield %>
　  </main>
  </body>

  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
  </body>
</html>

app/views/users/_user_info.html.erb
<h2>User info</h2>
 <%= image_tag user.get_profile_image(100, 100) %>
 <table class="table">
  <tbody>
   <tr>
   <th>name</th>
   <th><%= user.name %></th>
   </tr>
   <tr>
   <th>introduction</th>
   <th><%= user.introduction %></th>
   </tr>
  </tbody>
 </table>
 <div class="row">
  <a class="btn btn-outline-secondary btn-block" href="<%= edit_user_path(user.id) %>">
   <i class="fas fa-user-cog" aria-hidden="true" ></i>
  </a>
 </div>

app/views/users/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h2>User info</h2>
   <% if @user.errors.any? %>
   <%= @user.errors.count %>errors prohibited this obj from being saved:
   <ul>
   <% @user.errors.full_messages.each do |message| %>
   <li><%= message %></li>
   <% end %>
   </ul>
   <% end %>
   <%= form_with model: @user do |f| %>
   <div class="form-group">
   <label for="inputName">Name</label><br>
   <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name" %>
   </div>
   <div class="form-group">
   <label for="inputImage">Image</label><br>
   <%= f.file_field :profile_image, placeholder:"Image", accept: "image/*" %>
   </div>
   <div class="form-group">
   <label for="inputIntroduction">Introduction</label><br>
   <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"Introduction" %>
   </div>
   <div class="form-group">
   <%= f.submit "Update User", class: "btn btn-secondary" %>
   </div>
   <% end %>
  </div>
 </div>
</div>

app/views/users/index.html.erb
<div class = "flash_message">
 <%= flash[:notice] %>
</div>
 <div class="container px-5 px-sm-0">
  <div class="row">
   <div class="col-md-3">
    <%= render 'user_info', user: @user %>
    <%= render 'books/new', book: @book %>
  </div>
  <div class="col-md-8 offset-md-1">
   <h2>Users</h2>
   <table class="table">
   <thead>
    <tr>
    <th>image</th>
    <th>name</th>
    <th colspan="3"></th>
    </tr>
   </thead>
   <tbody>
    <% @users.each do |user| %>
    <tr>
    <td><%= image_tag user.get_profile_image(100, 100) %></td>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    </tr>
    <% end %>
   </tbody>
   </table>
  </div>
 </div>
</div>

 

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
  <%= render 'user_info', user: @user %>
  <%= render 'books/new', book: @book %>
  </div>
  <div class="col-md-8 offset-md-1">
   <%= render 'books/list', books: @books %>
  </div>
 </div>
</div>